# Generated by Django 3.1.1 on 2020-09-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mod_data',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='folder',
            field=models.CharField(blank=True, max_length=128, verbose_name=''),
        ),
    ]
