# Generated by Django 3.1.1 on 2020-09-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200909_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portrait',
            field=models.CharField(blank=True, max_length=256, verbose_name=''),
        ),
    ]
