# Generated by Django 3.1 on 2020-09-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200910_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='portrait',
            field=models.ImageField(default='media/default.png', upload_to='photo'),
        ),
    ]
