# Generated by Django 3.1 on 2020-09-21 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabeledImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_type', models.CharField(max_length=50, verbose_name='根分类')),
                ('sub_type', models.CharField(default='', max_length=50, verbose_name='子分类')),
                ('img_name', models.CharField(max_length=255, verbose_name='图片名')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='图片拥有者')),
            ],
        ),
    ]
